// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpbSvHWGq_LIMUfVIE63qi0XT1aPCKmu4',
    appId: '1:464994392705:web:4367c69638c0e0b6d40b80',
    messagingSenderId: '464994392705',
    projectId: 'fir-getx-app-9a165',
    authDomain: 'fir-getx-app-9a165.firebaseapp.com',
    storageBucket: 'fir-getx-app-9a165.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4VYVxJycx-XWyE2Lv9_BErrFF3cHt1tk',
    appId: '1:464994392705:android:a147c5167a7ade50d40b80',
    messagingSenderId: '464994392705',
    projectId: 'fir-getx-app-9a165',
    storageBucket: 'fir-getx-app-9a165.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSClavVcuodBc7pHmvDguSQmDP56tNJrc',
    appId: '1:464994392705:ios:a6180975fa13c0efd40b80',
    messagingSenderId: '464994392705',
    projectId: 'fir-getx-app-9a165',
    storageBucket: 'fir-getx-app-9a165.appspot.com',
    iosClientId: '464994392705-7ua95vrqn57185dkku97tts4levu7eq2.apps.googleusercontent.com',
    iosBundleId: 'com.example.emailLoginApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSClavVcuodBc7pHmvDguSQmDP56tNJrc',
    appId: '1:464994392705:ios:a6180975fa13c0efd40b80',
    messagingSenderId: '464994392705',
    projectId: 'fir-getx-app-9a165',
    storageBucket: 'fir-getx-app-9a165.appspot.com',
    iosClientId: '464994392705-7ua95vrqn57185dkku97tts4levu7eq2.apps.googleusercontent.com',
    iosBundleId: 'com.example.emailLoginApp',
  );
}
